### ISSUE TITLE
Skipping the intro of a map via spacebar crashes the game.

### ISSUE THREAD

**Issue by entwastaken** [EVAST9919/bosu#22]
this occurs on the latest release at the moment (514.1), when you press space to skip the intro of a map, the game crashes.

any map with a skippable intro works, and skipping it via clicking the SKIP button in the middle does not crash.
last version i know of that didn't crash is 512.2, i didn't check the ones released after that but before 514.1
[video](https://www.youtube.com/watch?v=tEZHR8qZv-s)

**Comment by EVAST9919** [comment]
I guess you have jump action binded to space button
If so - I'm aware 
Will try to fix that soon

**Comment by EVAST9919** [comment]
Fixed in the latest release
