### ISSUE TITLE
Beatmaps not loading when bosu! is selected

### ISSUE THREAD

**Issue by MasterIO02** [EVAST9919/bosu#23]
Hi! When I launch any songs/beatmaps with the bosu! ruleset, the game just hangs at the loading screen and says that an error has occured. In the logs it seems that it cannot load 'osu.Framework.Audio.Track.ISampleStore'.
I am on Linux, haven't tried on Windows.
I'm using the latest bosu! version (2021.118.0) and the latest osu!lazer version (2021.118.1).
Default and other custom rulesets are working fine.

Here is the full log:
[runtime.log](https://github.com/EVAST9919/bosu/files/5841681/runtime.log)

Have a nice day!

**Comment by EVAST9919** [comment]
Thanks for letting me know, will fix in the next update

**Comment by EVAST9919** [comment]
Fixed in 2021.121.0 update
