### ISSUE TITLE
Colorhax broken during gameplay

### ISSUE THREAD

**Issue by entwastaken** [EVAST9919/bosu#27]
Custom beatmap colour ordering (known as "colorhax") seems to break at random points, resulting in colours different from the intended ones being used in certain parts.

Map used for testing: https://osu.ppy.sh/beatmapsets/1920968#osu/3964993

In this map, only a few bat-shaped sliders use the black combo colour, with all other objects being red/orange. When played in bosu!, the map occasionally switches between red/orange, orange/black, black/red etc. with the aforementioned bat sliders "appropriately" using the third combo colour that happens to be unused at that point in the gameplay.

Video showcasing issue: https://youtu.be/3Ff-s2UHP0Y

bosu! build used: 2023.202.1
osu!lazer build used: 2023.123.0

**Comment by EVAST9919** [comment]
Fixed in the latest release
